
#ifndef CONFIG_H
#define CONFIG_H

#define FIRST_COME_FIRST_SERVE 0
#define SHORTEST_JOB_FIRST_PRE 1
#define SHORTEST_JOB_FIRST_NON_PRE 2
#define LONGEST_JOB_FIRST 3
#define PRIORITY_SCHEDULING 4
#define ROUND_ROBIN 5

#define CURRENT_ALGORITHM SHORTEST_JOB_FIRST_NON_PRE 

#define DEBUG_MODE true 
#define TESTING_MODE true 

#endif
